### ISSUE TITLE
Two messages after submitting to assignment

### ISSUE THREAD

**Issue by eyliu-00** [gavinmccabe/CS101-SP2021-Assignments-Submission#1]
I received two messages after submitting my assignment. The first one confirmed the submission and the second one said there was an internal server error.

**Comment by gavinmccabe** [comment]
@eyliu-00 Thanks for letting me know.  I've gotten a few reports of things going wrong this past night.  I've narrowed down the issue and will be working on a fix.  Please send me your zip file via email so I can manually upload in the meantime.

**Comment by gavinmccabe** [comment]
Fixed the issue, had to do with .jpeg and .pdf files.  You're free to re-submit on the website.

**Comment by eyliu-00** [comment]
Hi Gavin,

I am trying to resubmit on the website. Although I can select the zipped project directory, the submit button does not seem to be responding. Should I send my zip file to you via email for this assignment?

Elise

On Apr 30, 2021, at 5:15 AM, gavinmccabe ***@***.******@***.***>> wrote:



Fixed the issue, had to do with .jpeg and .pdf files. You're free to re-submit on the website.

**Comment by eyliu-00** [comment]
Hi Gavin,

Here is my submission for CP 2. Thank you!

Elise



On Apr 30, 2021, at 11:42 AM, gavinmccabe ***@***.******@***.***>> wrote:



Hi Elise, that's really weird I didn't see any error messages and everything is working for me. Go ahead and email me the zip file and I'll manually upload it. Sorry about that!

**Comment by gavinmccabe** [comment]
@eyliu-00 I just noticed I never got a file from you (I don't think GitHub automatically includes the attachments through email).  Could you email me at gavin (at) caltech (dot) edu?
